language: go
go:
  - 1.5
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
install:
  - go get -d -v ./...
script:
  - go install ./...
  - PATH=$PATH:$GOPATH/bin/path ./run_test.sh
after_success:
  - $GOPATH/bin/gox -cgo -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - $GOPATH/bin/ghr --username edvakf --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
